// web/src/pages/Chat/index.tsx
import './styles.scss'

import React from 'react';
import { useHistory } from "react-router-dom";

import { User } from "../../classes/User";
import Header from "../../components/Header";

interface ChatProps {
	currentUser: User,
	setCurrentUser: (arg0: User) => void
}

const Chat = (props: ChatProps) => {
	const history = useHistory();

	React.useEffect(() => {
		if (!props.currentUser.isAuthorized())
			history.push('/login')
	}, [history, props.currentUser])

	return (
		<div className='chat-container'>
			<Header
				currentUser={props.currentUser}
				setCurrentUser={props.setCurrentUser}
			/>
			Chat view
		</div>
	)
}

export default Chat;

// web/src/views/Chat.vue
<template>
	<div>
		<Header :user="this.user"/>
		Chat view
	</div>
</template>

<script lang="ts">
import Header from "@/components/Header.vue";
import router from "@/router/index.ts";
import User from "@/User.ts";
import {defineComponent} from "vue";

export default defineComponent ({
	name: "Chat",
	components: {Header},
	props: {
		user: {
			type: User,
			required: true
		}
	},
	beforeMount(): void {
		if (!this.user.isAuthorized())
			router.push('/login')
	}
})
</script>

<style scoped>

</style>
