// web/src/pages/Register/index.tsx
import './styles.scss';

import axios, { AxiosResponse } from "axios";
import * as bcryptjs from 'bcryptjs';
import CircleLoading from "components/CircleLoading";
import { UserCheckExist, UserCreate } from "models/apiTypes";
import { User } from "models/User";
import { signIn } from "pages/Login";
import React from 'react';
import { Link, useHistory } from "react-router-dom";

const validateInput = (
	login: string,
	password: string,
	passwordConfirmation: string,
	setErrors: React.Dispatch<React.SetStateAction<string> >
): boolean => {
	if (!login) {
		setErrors('Enter login');
		return false;
	}
	if (!password) {
		setErrors('Enter password');
		return false;
	}
	if (login.length < 4) {
		setErrors('Login is too short');
		return false;
	}
	if (login.length > 16) {
		setErrors('Login is too long');
		return false;
	}
	if (password.length < 6) {
		setErrors('Password is too short');
		return false;
	}
	if (password !== passwordConfirmation) {
		setErrors('Passwords are not equal');
		return false;
	}
	setErrors('');
	return true;
};

interface RegisterProps {
	currentUser: User,
	setCurrentUser: React.Dispatch<React.SetStateAction<User> >
}

const Register = ({ currentUser, setCurrentUser }: RegisterProps) => {
	const history = useHistory();

	React.useEffect(() => {
		if (currentUser.isAuthorized())
			history.push('/');
	}, [history, currentUser]);

	const loginRef = React.createRef<HTMLInputElement>();
	const passwordRef = React.createRef<HTMLInputElement>();
	const passwordConfirmRef = React.createRef<HTMLInputElement>();

	const [errors, setErrors] = React.useState<string>('');
	const [isLoading, setIsLoading] = React.useState<boolean>(false);

	const register = async (e: React.FormEvent) => {
		e.preventDefault();

		const login = loginRef.current?.value || '';
		const password = passwordRef.current?.value || '';
		const passwordConfirm = passwordConfirmRef.current?.value || '';

		if (!validateInput(login, password, passwordConfirm, setErrors))
			return;

		setIsLoading(true);
		setErrors('');
		const checkExistResponse: UserCheckExist = await axios.get<UserCheckExist>('/users/checkExist', {
			params: { login: login }
		})
			.then(res => res.data);
		if (checkExistResponse.ok) {
			setErrors('User with this login already exists');
			setIsLoading(false);
			return;
		}

		const hashedPassword = await bcryptjs.hash(password, 10);
		const usersCreateResponse = await axios.post<any, AxiosResponse<UserCreate> >(
			'/users/create', {
			login: login,
			pass: hashedPassword
		})
			.then(res => res.data);
		if (usersCreateResponse.ok) {
			await signIn(login, password, setCurrentUser, setErrors)
				.catch(err => setErrors(err.toString()));
		} else {
			setErrors(usersCreateResponse.msg);
		}
		setIsLoading(false);
	};

	return (
		<div className='register-container'>
			<h1>Registration</h1>

			<form
				onSubmit={register}
			>
				<input
					name='login'
					type='text'
					placeholder='Login'
					ref={loginRef}
					autoComplete='username'
				/>
				<input
					name='password'
					type='password'
					placeholder='Password'
					ref={passwordRef}
					autoComplete='new-password'
				/>
				<input
					name='password-confirm'
					type='password'
					placeholder='Confirm password'
					ref={passwordConfirmRef}
					autoComplete='new-password'
				/>
				<span className='errors'>
					{errors}
				</span>
				<button type='submit' className='register-btn'>
					{
						isLoading ?
							<CircleLoading bgColor='#fff' width='35px' height='35px'/> :
							<span>Register</span>
					}
				</button>
			</form>

			<span className='separator'>
				Or
			</span>

			<Link className='register-link' to='/login'>
				Sign in
			</Link>
		</div>
	);
};

export default Register;

// web/src/views/Register.vue
<template>
	<div v-if="!user.isAuthorized()" class="container">
		<h1>Registration</h1>

		<form
			v-on:submit.prevent="register()"
		>
			<input
				name="log"
				type="text"
				placeholder="Login"
				v-model="inputLogin"
			/>
			<input
				name="pass"
				type="password"
				placeholder="Password"
				v-model="inputPassword"
			/>
			<input
				name="pass-confirm"
				type="password"
				placeholder="Confirm password"
				v-model="inputPasswordConfirmation"
			/>

			<span class="errors">
				{{ errors }}
			</span>

			<button
				type="submit"
				class="login-btn"
			>
				<CircleLoading
					v-if="isLoading"
					bg-color="white"
					height="35px"
					width="35px"
				/>
				<span v-else>
					Register
				</span>
			</button>
		</form>

		<span class="separator">Or</span>

		<router-link class="register-link" to="/login">
			Sign in
		</router-link>
	</div>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import CircleLoading from "@/components/CircleLoading.vue";
import User from "@/User";
import router from "@/router";
import axios from "axios";
import * as bcryptjs from 'bcryptjs';
import {userCreate, userLogin} from "@/apiTypes/apiTypes";

export default defineComponent({
	name: "Register",
	components: {CircleLoading},
	props: {
		user: {
			type: User,
			required: true
		}
	},
	methods: {
		async register() {
			// validation
			if (!this.validate())
				return

			this.isLoading = true
			let r = await axios.get('http://localhost:3000/users/checkExist', {
				params: { login: this.inputLogin }
			})
				.then(res => res.data)
			if (r) {
				this.errors = 'User with the same login already exists'
				this.isLoading = false
				return
			}
			await bcryptjs.hash(this.inputPassword, 10).then(res => { this.hashedPass = res })
			const createRes: userCreate = await axios.post('http://localhost:3000/users/create', {
				login: this.inputLogin,
				pass: this.hashedPass
			})
				.then(res => res.data)
				.catch(err => this.errors = err)
			if (createRes.ok) {
				// Successful registration, getting user
				const loginRes: userLogin = await axios.post('http://localhost:3000/users/login', {login: this.inputLogin})
					.then(res => {
						return res.data
					})
					.catch(err => this.errors = err)
				if (loginRes.id === undefined) {
					this.errors = 'Wrong login or password!'
					this.isLoading = false
					return
				}
				if (bcryptjs.compareSync(this.inputPassword, loginRes.password)) {
					const user = new User();
					user.username = loginRes.login
					user.loginDate = Date.now()

					this.$emit('update:user', user)
					this.errors = ''
					await router.push('/')
				} else {
					this.inputPassword = ''
					this.errors = 'Wrong login or password!'
				}
			} else {
				this.errors = createRes.msg
			}
			this.isLoading = false
		},
		validate() {
			if (!this.inputLogin) {
				this.errors = 'Enter login'
				return false
			}
			if (!this.inputPassword) {
				this.errors = 'Enter password'
				return false
			}
			if (this.inputLogin.length < 4) {
				this.errors = 'Login is too short'
				return false
			}
			if (this.inputLogin.length > 16) {
				this.errors = 'Login is too long'
				return false
			}
			if (this.inputPassword.length < 6) {
				this.errors = 'Password is too short'
				return false
			}
			if (this.inputPassword !== this.inputPasswordConfirmation) {
				this.errors = 'Passwords are not equal'
				return false
			}
			this.errors = ''
			return true
		}
	},
	data() {
		return {
			inputLogin: '',
			inputPassword: '',
			inputPasswordConfirmation: '',
			errors: '',
			isLoading: false,
			hashedPass: ''
		}
	},
	beforeMount(): void {
		if (this.user.isAuthorized())
			router.push('/')
	}
})
</script>

<style scoped lang="scss">

.container {
	margin: 0 auto;
	width: 1024px;
	height: calc(100vh - 101px);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;

	h1 {
		margin-bottom: 30px;
	}

	form {
		display: flex;
		flex-direction: column;
	}

	input {
		border-radius: 15px;
		width: calc(400px - 40px);
		border: 1px solid #2c3e50;
		outline: none;
		font-size: 1em;
		padding: 12px 20px;
		margin-bottom: 15px;
		transition: all 0.1s ease-in;

		&:focus {
			border-color: #42b983;
		}
	}

	button {
		border-radius: 15px;
		cursor: pointer;
		width: 400px;
		height: 50px;
		font-size: 1.2em;
		font-weight: bold;
		padding: 10px 12px;
		background: #42b983;
		border: none;
		outline: none;
		color: white;
		display: flex;
		justify-content: center;
		align-items: center;
		transition: all 0.1s ease-in;

		@media (hover: hover) {
			&:hover {
				background: #42ad7b;
			}
		}
	}

	.errors {
		margin-bottom: 15px;
		color: red;
	}

	.register-link {
		color: #42b983;
		font-size: 1.2em;
		width: fit-content;
		padding: 0;

		&:hover {
			text-decoration: underline;
		}
	}

	.separator {
		margin: 30px 0;
	}
}

</style>
